version: "3"
services:
 haproxy:
  image: dockercloud/haproxy
  deploy:
   mode: global
   update_config:
    parallelism: 1
    delay: 5s
   resources:
    limits:
     cpus: "0.05"
     memory: 64M
    reservations:
     cpus: "0.01"
     memory: 20M
   restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3
   placement:
    constraints: [node.role == manager]
  volumes:
   - '/var/run/docker.sock:/var/run/docker.sock'
  networks:
   - proxy
   ports:
   - "80:80"


 helloworld:
  image: dockercloud/hello-world
  networks:
   - proxy
  deploy:
   replicas: 4
  environment:
   - SERVICE_PORTS="80"
   - VIRTUAL_HOST=http://hello.homecolis.ab
networks:
 proxy:
  external: true
